apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crossplane-project
  namespace: argocd
spec:
  description: Crossplane infrastructure management project
  sourceRepos:
    - "*"
  destinations:
    - namespace: crossplane-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: crossplane-admin
      description: Administrator role for Crossplane project
      policies:
        - p, proj:crossplane-project:crossplane-admin, applications, *, crossplane-project/*, allow
        - p, proj:crossplane-project:crossplane-admin, repositories, *, *, allow
      groups:
        - crossplane-admins
