apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Resource tracking configuration
  application.resourceTrackingMethod: annotation
  
  # Exclude ProviderConfigUsage to prevent unnecessary reconciliation
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ProviderConfigUsage
  
  # Custom health checks for Crossplane resources
  resource.customizations: |
    "*.upbound.io/*":
      health.lua: |
        health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" then
                if condition.status == "True" then
                  health_status.status = "Healthy"
                  health_status.message = "Resource is ready"
                  return health_status
                else
                  health_status.status = "Progressing"
                  health_status.message = "Waiting for resource to be ready"
                  return health_status
                end
              end
            end
          end
        end
        health_status.status = "Progressing"
        health_status.message = "Waiting for resource status"
        return health_status
    "*.oci.upbound.io/*":
      health.lua: |
        health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" then
                if condition.status == "True" then
                  health_status.status = "Healthy"
                  health_status.message = "Resource is ready"
                  return health_status
                else
                  health_status.status = "Progressing"
                  health_status.message = "Waiting for resource to be ready"
                  return health_status
                end
              end
            end
          end
        end
        health_status.status = "Progressing"
        health_status.message = "Waiting for resource status"
        return health_status