apiVersion: containerengine.oci.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: test-oke-cluster
  labels:
    testing.upbound.io/example-name: test-oke-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  forProvider:
    compartmentId: "ocid1.compartment.oc1..aaaaaaaahkmcqkcdnvjxdykdiai4ncm5f4o3n3gmtbpy6cnvey2nspef6k5a"
    name: test-oke-cluster
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-vcn
    type: "BASIC_CLUSTER"
    kubernetesVersion: "v1.33.1"
    
    # Cluster endpoint configuration
    endpointConfig:
    - isPublicIpEnabled: true
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test-subnet
    
    # Cluster pod network options
    clusterPodNetworkOptions:
    - cniType: "FLANNEL_OVERLAY"
    
    # Cluster options
    options:
    - addOns:
      - isKubernetesDashboardEnabled: false
        isTillerEnabled: false
      admissionControllerOptions:
      - isPodSecurityPolicyEnabled: false
      kubernetesNetworkConfig:
      - podsCidr: "10.244.0.0/16"
        servicesCidr: "10.96.0.0/16"
      serviceLbSubnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test-subnet
  providerConfigRef:
    name: default
