apiVersion: containerengine.oci.upbound.io/v1alpha1
kind: NodePool
metadata:
  name: test-node-pool
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,RespectIgnoreDifferences=true,ServerSideApply=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  forProvider:
    compartmentId: "ocid1.compartment.oc1..aaaaaaaahkmcqkcdnvjxdykdiai4ncm5f4o3n3gmtbpy6cnvey2nspef6k5a"
    name: test-node-pool
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-oke-cluster
    nodeShape: VM.Standard.E4.Flex
    nodeShapeConfig:
      - memoryInGbs: 16
        ocpus: 1
    nodeConfigDetails:
      - size: 1
        placementConfigs:
          - availabilityDomain: "ekzo:US-ASHBURN-AD-1"
            subnetIdRef:
              name: test-subnet
    nodeSourceDetails:
      - imageId: "ocid1.image.oc1.iad.aaaaaaaagj4j3vtqhfgjqbmftiqpa6jxhpelhxn4otvnsvbjrclqvkwd3xaq"  # Oracle Linux 7.9
        sourceType: "IMAGE"
  providerConfigRef:
    name: default