apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-oci
spec:
  package: iad.ocir.io/iddevjmhjw0n/provider-family-oci:v0.1.0-test-arm64
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1