apiVersion: networking.oci.upbound.io/v1alpha1
kind: Subnet
metadata:
  name: test-node-subnet
  labels:
    testing.upbound.io/example-name: test-node-subnet
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  forProvider:
    cidrBlock: "10.0.2.0/24"  # Dedicated CIDR for worker nodes
    compartmentId: "ocid1.compartment.oc1..aaaaaaaahkmcqkcdnvjxdykdiai4ncm5f4o3n3gmtbpy6cnvey2nspef6k5a"
    displayName: "test-node-subnet"
    dnsLabel: "testnodes"
    vcnIdRef:
      name: test-vcn
  providerConfigRef:
    name: default