apiVersion: networking.oci.upbound.io/v1alpha1
kind: SecurityList
metadata:
  name: test-oke-security-list
  labels:
    testing.upbound.io/example-name: test-oke-security-list
    seclist.name: oke
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    compartmentId: "ocid1.compartment.oc1..aaaaaaaahkmcqkcdnvjxdykdiai4ncm5f4o3n3gmtbpy6cnvey2nspef6k5a"
    displayName: "test-oke-seclist"
    vcnIdRef:
      name: test-vcn
    
    # Ingress rules
    ingressSecurityRules:
      # Allow all traffic within VCN
      - description: "Allow all traffic within VCN"
        protocol: "all"
        source: "10.0.0.0/16"
        stateless: false
      
      # Allow SSH from anywhere (restrict in production)
      - description: "Allow SSH traffic"
        protocol: "6"
        source: "0.0.0.0/0"
        stateless: false
        tcpOptions:
          - min: 22
            max: 22
      
      # Allow Kubernetes API access
      - description: "Allow Kubernetes API traffic"
        protocol: "6"
        source: "0.0.0.0/0"
        stateless: false
        tcpOptions:
          - min: 6443
            max: 6443
    
    # Egress rules
    egressSecurityRules:
      # Allow all outbound traffic
      - description: "Allow all outbound traffic"
        protocol: "all"
        destination: "0.0.0.0/0"
        stateless: false
        
  providerConfigRef:
    name: default