apiVersion: core.oci.upbound.io/v1alpha1
kind: RouteTable
metadata:
  name: oke-route-table
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  forProvider:
    compartmentId: "ocid1.compartment.oc1..aaaaaaaavn2sncyioaydldub5sbu44yolvenr44fcsb57vtu3z6mxhizndva"
    displayName: "oke-route-table"
    vcnIdRef:
      name: oke-vcn
  providerConfigRef:
    name: default
