apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-compute
spec:
  package: ghcr.io/oracle-samples/provider-oci-compute:v0.0.1-alpha.1-amd64
  # packagePullSecrets:
  # - name: ocir-secret
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  # This provider depends on the family provider
  skipDependencyResolution: false
