apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oci-provider.yaml
  - provider-config.yaml
# Secrets are deployed manually - not via GitOps
# See secrets/README.md for deployment instructions

# Note: Provider is cluster-scoped, ProviderConfig is namespaced
# We'll handle namespacing in the individual resource files
