apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-oci
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: iad.ocir.io/idwsb3nvxazj/provider-oci:v1.0
  packagePullSecrets:
    - name: ocir-secret
  runtimeConfigRef:
    name: oci-runtime-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: oci-runtime-config
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
