apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-oci
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: iad.ocir.io/iddevjmhjw0n/provider-oci:v1.0-arm64-tf-7.10.0
  # packagePullSecrets:
  #   - name: ocir-secret
  runtimeConfigRef:
    name: oci-runtime-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: oci-runtime-config
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              resources:
                limits:
                  cpu: 2000m
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 512Mi
