apiVersion: identity.oci.upbound.io/v1alpha1
kind: Compartment
metadata:
  name: test-compartment
spec:
  forProvider:
    description: "Test compartment created by Crossplane"
    name: "test-compartment"
    # Parent compartment - using the same compartment from examples
    compartmentId: "ocid1.compartment.oc1..aaaaaaaavn2sncyioaydldub5sbu44yolvenr44fcsb57vtu3z6mxhizndva"
  providerConfigRef:
    name: default
