apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-oci-containerengine
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/davidcv5/crossplane-gitops
    targetRevision: sub-package
    path: crossplane/providers/oci-sub-packages/containerengine
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  # Ensure family provider is healthy before syncing
  health:
    healthChecks:
    - kind: Provider
      name: provider-family-oci
      namespace: crossplane-system
