apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - family
  - identity
  - networking
  - containerengine
  - objectstorage
  - loadbalancer
  - networkloadbalancer
  - certificatesmanagement
  - kms