apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Essential components for OKE cluster
  - networking
  - containerengine
  
  # Optional components (disabled for minimal cluster)
  # - objectstorage      # Not needed for cluster functionality
  # - loadbalancer       # Not needed (OKE has built-in LB support)
  # - networkloadbalancer
  # - certificatesmanagement
